.PHONY: clean All

All:
	@echo "----------Building project:[ MyStringInsertionExtraction - Debug ]----------"
	@cd "MyStringInsertionExtraction" && "$(MAKE)" -f  "MyStringInsertionExtraction.mk"
clean:
	@echo "----------Cleaning project:[ MyStringInsertionExtraction - Debug ]----------"
	@cd "MyStringInsertionExtraction" && "$(MAKE)" -f  "MyStringInsertionExtraction.mk" clean
