.PHONY: clean All

All:
	@echo "----------Building project:[ RedefiningBassClassMethods - Debug ]----------"
	@cd "RedefiningBassClassMethods" && "$(MAKE)" -f  "RedefiningBassClassMethods.mk"
clean:
	@echo "----------Cleaning project:[ RedefiningBassClassMethods - Debug ]----------"
	@cd "RedefiningBassClassMethods" && "$(MAKE)" -f  "RedefiningBassClassMethods.mk" clean
