.PHONY: clean All

All:
	@echo "----------Building project:[ CopyFile_1 - Debug ]----------"
	@cd "CopyFile_1" && "$(MAKE)" -f  "CopyFile_1.mk"
clean:
	@echo "----------Cleaning project:[ CopyFile_1 - Debug ]----------"
	@cd "CopyFile_1" && "$(MAKE)" -f  "CopyFile_1.mk" clean
